#   rest client requests    #
#   id: humao.rest-client   #
#       PERSON LOOKUP       #


### FIND BY PHONE NUMBER ###
GET http://localhost:5000/api/v1/person/phone?number=<NUMBER> HTTP/1.1

### FIND BY NAME AND SURNAME ###
GET http://localhost:5000/api/v1/person/find?name=<NAME>&surname=<SURNAME> HTTP/1.1

### DELETE BY ID ###
DELETE  http://localhost:5000/api/v1/person/delete?id=<ID> HTTP/1.1

###ADD/SAVE A NEW USER###
POST http://localhost:5000/api/v1/person/add/ HTTP/1.1
content-type: application/json

{
    "phonenum": "1234567890",
    "fbid": "1234567890",
    "name": "Name",
    "surname": "Surname",
    "sex": "male",
    "extra": "extra info about the person"
}


###
PATCH http://localhost:5000/api/v1/person/update/ HTTP/1.1
content-type: application/json

{
    "_id": "622345623dc...",
    "phonenum": "1234567890",
    "fbid": "1234567890",
    "name": "Name",
    "surname": "Surname",
    "sex": "male",
    "extra": "extra info about the person"
}


#-----CAR LOOKUP-----#


### PLATES LOOKUP (HR) ###
GET http://localhost:5000/api/v1/carlookup/hr?plates=ZGXXXXXX HTTP/1.1


### PLATES LOOKUP (BIH) ###
GET http://localhost:5000/api/v1/carlookup/bih?plates=E94-X-XXX HTTP/1.1

### VIN LOOKUP (HR) ###
GET http://localhost:5000/api/v1/carlookup/vin?number=<VINNUMBER>&month=3 HTTP/1.1



#-----NMAP-----#


### ping scan ###
GET http://localhost:5000/api/v1/nmap/ping?target=google.com HTTP/1.1

### traceroute ###
GET http://localhost:5000/api/v1/nmap/traceroute?target=google.com HTTP/1.1

### intense scan  [!] SLOW ###
GET http://localhost:5000/api/v1/nmap/intscan?target=google.com HTTP/1.1 

### intense TCP scan [!] SLOW ###
GET http://localhost:5000/api/v1/nmap/intscantcp?target=google.com HTTP/1.1

### intense UDP scan [!] SLOW ###
GET http://localhost:5000/api/v1/nmap/intscanudp?target=google.com HTTP/1.1

### quick scan ###
GET http://localhost:5000/api/v1/nmap/quickscan?target=google.com HTTP/1.1

#### WHOIS lookup #####
GET http://localhost:5000/api/v1/whois?domain=google.com HTTP/1.1


#### Subdomain scan [!] slow scan most of the time #####
GET http://localhost:5000/api/v1/nmap/subdomains?domain=google.com HTTP/1.1